spring.jpa.database=POSTGRESQL
spring.datasource.platform=postgres
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/Prueba
spring.datasource.username=postgres
spring.datasource.password=0102
spring.jpa.generate-ddl=true
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
jwt.secret=e1c9b8a7f6d5c4b3a2f1e0d9c8b7a6f5e4d3c2b1a0f9e8d7c6b5a4f3e2d1c0b9
jwt.expiration=86400000
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true